services:
  networthdb:
    container_name: networthdbcontainerv1
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mariadb
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MARIADB_ROOT_PASSWORD: 2007
      MARIADB_PASSWORD: 2007
      MARIADB_DATABASE: networth
      MARIADB_USER: admin
      SERVICE_NAME: networthdb
    networks:
      - internalnet
  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: networth:v1
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - networthdb
    environment:
      PORT: 3000
      HOST: localhost
      USER: root
      DB: networth
      PASSWORD: 2007
      JWT_ACCESS_SECRET: shodon2007
      JWT_REFRESH_SECRET: shodon2007
      SMTP_HOST: smtp.mail.ru
      SMTP_PORT: 465
      SMTP_USER: help.networth@mail.ru
      SMTP_PASSWORD: 4QVfLxEfLYRgZ9JcSJSF
      API_URL: https://networth.shodon.ru
      CLIENT_URL: https://store.shodon.ru
      SERVICE_PORT: 3000
      SERVICE_TAGS: prod
      SERVICE_NAME: networthnode
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge
